######################################################################
# Automatically generated by qmake (2.01a) Thu May 28 11:14:23 2009
######################################################################

TEMPLATE = app
TARGET = ../../bin/pdif
DEPENDPATH += .
INCLUDEPATH += .

# Input
CONFIG += qt 
HEADERS += pdif.h
SOURCES += main.cpp pdif.cpp
RESOURCES += pdif.qrc
RC_FILE = pdif.rc
