######################################################################
# Automatically generated by qmake (2.01a) Fri Jul 19 11:27:05 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += uname.cpp
